# frozen_string_literal: true

module DocsKit
  # The per-site SEO / social-share knobs, read by DocsUI::MetaTags to emit the
  # <head> meta/link tags (description, Open Graph, Twitter Card, canonical,
  # favicon, theme-color). Nested under DocsKit::Configuration#seo so a site
  # configures it as a small block:
  #
  #   DocsKit.configure do |c|
  #     c.seo.description  = "What these docs cover, in one sentence."
  #     c.seo.og_image     = "og/og.png"        # generated by `bin/rails docs_kit:og`
  #     c.seo.twitter_site = "@my_handle"
  #   end
  #
  # Every field defaults to a backwards-safe value: a site that sets none still
  # renders a valid minimal Open Graph block and no broken empty tags. Plain
  # accessors (not Data.define) because each field is individually assignable in
  # the `c.seo.x = ...` block, mirroring DocsKit::Configuration's own style.
  class SeoConfig
    # A one-line page/site description → <meta name="description"> and
    # og:description / twitter:description. nil omits the description tags
    # (DocsUI::Page derives a per-page value from #lead when a page sets none).
    attr_accessor :description

    # The social-share image, as an asset path (resolved via the Rails asset
    # helper) or an absolute URL → og:image / twitter:image. Defaults to the
    # neutral image docs-kit ships at app/assets/images/og/og.png so og:image is
    # never broken; a site regenerates its own with `bin/rails docs_kit:og`.
    attr_accessor :og_image

    # The og:type. "website" for a docs site; a page could override to "article".
    attr_accessor :og_type

    # The twitter:card style. "summary_large_image" renders a full-width banner
    # (the shipped og:image is 1200×630, sized for it); "summary" is the small
    # square card.
    attr_accessor :twitter_card

    # The site's @handle → twitter:site, and the content author's → twitter:creator.
    # Both nil by default (a site with no X presence emits neither tag).
    attr_accessor :twitter_site, :twitter_creator

    # The og:locale (e.g. "en_US", "sv_SE").
    attr_accessor :locale

    # The site's canonical base URL (e.g. "https://docs.example.com"). When set,
    # og:image/og:url/canonical are absolutized against it even off a request
    # (a static build, an isolated render). nil → DocsUI::MetaTags falls back to
    # the request base URL, and omits canonical/absolute og:url when there's no
    # request either.
    attr_accessor :site_url

    # A robots directive (e.g. "noindex, nofollow") → <meta name="robots">. nil
    # omits the tag, so the page is indexable by default.
    attr_accessor :favicon

    # A favicon asset path/URL → <link rel="icon">. nil omits the link (the host
    # may serve /favicon.ico itself).
    attr_accessor :robots

    # A theme-color (e.g. "#0f172a") → <meta name="theme-color">, tinting mobile
    # browser chrome. nil omits the tag.
    attr_accessor :theme_color

    def initialize
      @description     = nil
      @og_image        = "og/og.png"
      @og_type         = "website"
      @twitter_card    = "summary_large_image"
      @twitter_site    = nil
      @twitter_creator = nil
      @locale          = "en_US"
      @site_url        = nil
      @robots          = nil
      @favicon         = nil
      @theme_color     = nil
    end
  end
end
