name: Reusable docs deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      service:
        required: true
        type: string
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "reusable workflow reached, image=${{ inputs.image }} service=${{ inputs.service }}"
