name: Reusable docs deploy
on:
  workflow_call:
    inputs:
      image: { required: true, type: string }
      service: { required: true, type: string }
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "token is ${{ github.token != '' }}"
